// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIsu2uYDaT069GdtBAkWvp8I8_gYlPf4M',
    appId: '1:812093361434:android:ceaefbfa15fd41af4270a3',
    messagingSenderId: '812093361434',
    projectId: 'eventivo-3ade9',
    storageBucket: 'eventivo-3ade9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRRSvue_W_Uri7PDl_VvXPwpBR8LH6g6U',
    appId: '1:812093361434:ios:9a4f8971acafcf2f4270a3',
    messagingSenderId: '812093361434',
    projectId: 'eventivo-3ade9',
    storageBucket: 'eventivo-3ade9.firebasestorage.app',
    iosBundleId: 'com.example.eventivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRRSvue_W_Uri7PDl_VvXPwpBR8LH6g6U',
    appId: '1:812093361434:ios:9a4f8971acafcf2f4270a3',
    messagingSenderId: '812093361434',
    projectId: 'eventivo-3ade9',
    storageBucket: 'eventivo-3ade9.firebasestorage.app',
    iosBundleId: 'com.example.eventivo',
  );
}
